# Animation configuration (English) / アニメーションの設定 (日本語) / Configuración de la animación (Español)
animacion: true          # Whether the animation is enabled or not (English) / アニメーションが有効かどうか (日本語) / Si la animación está activada o no (Español)
unicode_inicial: '\uE000' # Initial Unicode for the animation frames (English) / アニメーションのフレームのための初期Unicode (日本語) / Unicode inicial para los fotogramas de la animación (Español)
numero_de_fotogramas: 92  # Total number of animation frames (English) / アニメーションの総フレーム数 (日本語) / Número total de fotogramas de la animación (Español)
velocidad_animacion: 1   # Animation speed in ticks, 20 ticks = 1 second (English) / アニメーションの速度（ティック単位）、20 ティック = 1秒 (日本語) / Velocidad de la animación en ticks, 20 ticks = 1 segundo (Español)

# Commands that will be executed during the animation (English) / アニメーション中に実行されるコマンド (日本語) / Comandos que se ejecutarán al momento de la animación (Español)
comandos:
  - 'title @a actionbar {"text":"{player} ha muerto","color":"red"}'

# Sound configuration (English) / 音の設定 (日本語) / Configuración de sonido (Español)
sonido:
  activar: true            # Enable/disable custom sound (English) / カスタムサウンドを有効/無効にする (日本語) / Activar/desactivar el sonido personalizado (Español)
  volumen: 1.0              # Sound volume (from 0.0 to 1.0) (English) / サウンドのボリューム（0.0から1.0まで）(日本語) / Volumen del sonido (de 0.0 a 1.0) (Español)
  pitch: 1.0                # Sound pitch (from 0.5 to 2.0) (English) / サウンドのピッチ（0.5から2.0まで）(日本語) / Pitch del sonido (de 0.5 a 2.0) (Español)

# Wait time for the 'title' command (in ticks) (English) / 'title' コマンドの待機時間（ティック単位）(日本語) / Tiempo de espera para el comando 'title' (en ticks) (Español)
title_wait: 40 # 20 ticks by default, which is 1 second (English) / デフォルトで20ティック、つまり1秒 (日本語) / 20 ticks por defecto, es decir, 1 segundo (Español)